### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ghost** [ryanmuinos/Fantasy-Premier-League-Tools#1]
I cloned your repo and uploaded the files on web server. Its not working. Am i missing something? 
Here is the [link ](https://www.fplnepal.com/check/)

**Comment by ryanmuinos** [comment]
Hi! I am not finished yet so I haven't done the index page. But try going to ./players.html to check out what I have so far.

**Comment by ghost** [comment]
Oh Sorry . Eagerly waiting . I am also learning webapp development too. Like JS and all. This project will be base.
